framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            import_process:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    exchange: { name: 'import_process', type: direct }
                    queues:
                        import_process: ~
            table_content_importer:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    exchange: { name: 'table_content_importer', type: direct }
                    queues:
                        table_content_importer: ~

        routing:
            'App\Messenger\Message\ImportProcess': import_process
            'App\Messenger\Message\TableContentImporter': table_content_importer
