version: "3.8"
services:
    mysql:
        container_name: it_mysql
        image: mysql:8.0
        working_dir: /application
        volumes:
            - ../:/application
            - ./data/mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=pass
            - MYSQL_DATABASE=db

    nginx:
        container_name: it_nginx
        image: nginx:alpine
        working_dir: /application
        volumes:
            - ../:/application
            - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./log/nginx:/var/log/nginx
        ports:
            - "80:80"
            - "443:443"

    php:
        container_name: it_php
        build: .
        working_dir: /application
        volumes:
            - ../:/application

    rabbitmq:
        image: rabbitmq:3.10-management
        container_name: it_rabbitmq
        ports:
            - "15672:15672"
            - "5672:5672"
        hostname: it
        environment:
            RABBITMQ_NODENAME: it_node
            RABBITMQ_DEFAULT_USER: root
            RABBITMQ_DEFAULT_PASS: pass
        volumes:
            - ./data/rabbitmq/:/var/lib/rabbitmq/mnesia
            - ./log/rabbitmq:/var/log/rabbitmq
