version: "3.8"
services:
    mysql:
        container_name: it_mysql
        image: mysql:8.0
        working_dir: /application
        volumes:
            - ../:/application
            - ./data/mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=$DB_PASSWORD"
            - MYSQL_DATABASE=db

    nginx:
        container_name: it_nginx
        image: nginx:alpine
        working_dir: /application
        volumes:
            - ../:/application
            - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./log/nginx:/var/log/nginx
        ports:
            - "80:80"
            - "443:443"

    php:
        container_name: it_php
        build: .
        working_dir: /application
        volumes:
            - ../:/application
